version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: DockerizedWebApiAndDB/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=SocialNetwork;User Id=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=True;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: mssql-custom-container
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD} 
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: